name: deployment
on:
  workflow_dispatch:
  pull_request:
     types:
       - opened
       - synchronize
       - reopened

env:
  NODE_VERSION: '24'
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./FE/package-lock.json

      - name: Install dependencies
        working-directory: ./FE
        run: |
          echo $(node -v)
          echo $(pwd)
          echo $(ls)
          npm ci
      - name: test frontend
        working-directory: ./FE
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./FE/package-lock.json
      - name: Build project
        run: |
          echo $(pwd)
          echo $(ls)
          cd ./FE
          echo $(pwd)
          echo $(ls)
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fe-dist
          path: ./FE/dist
  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: fe-dist
      - name: Deploy
        run: |
          echo $(pwd)
          echo $(ls)
          echo $NODE_VERSION
          echo "$NODE_VERSION"
          echo ${{ secrets.RANDOM_THING }}
          env
