name: test-fe
on: push
jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: test frontend
        working-directory: ./FE
        run: |
          pwd
          npm install
          npm run test
