name: test-fe
on: push
jobs:
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: test frontend
        working-directory: ./FE
        run: |
          echo $(node -v)
          echo $(pwd)
          echo $(ls)
          npm ci
          npm run test
